import { provideHttpClient } from "@angular/common/http";
import { provideRouter } from "@angular/router";
import { routes } from "./app.routes";

export const appConfig = {
  providers: [provideRouter(routes), provideHttpClient()],

  APIBaseUrl: "https://free-to-play-games-database.p.rapidapi.com/api",
  APIKey: "7a62723aeamsh5050565aa037217p1f2185jsnb774f53ca4e4",
  options: {
    headers: {
      "X-RapidAPI-Key": "7a62723aeamsh5050565aa037217p1f2185jsnb774f53ca4e4",
      "X-RapidAPI-Host": "free-to-play-games-database.p.rapidapi.com",
    },
  },
  categories: [
    "mmorpg",
    "shooter",
    "strategy",
    "moba",
    "racing",
    "sports",
    "social",
    "sandbox",
    "open-world",
    "survival",
    "pvp",
    "pve",
    "pixel",
    "voxel",
    "zombie",
    "turn-based",
    "first-person",
    "third-Person",
    "top-down",
    "tank",
    "space",
    "sailing",
    "side-scroller",
    "superhero",
    "permadeath",
    "card",
    "battle-royale",
    "mmo",
    "mmofps",
    "mmotps",
    "3d",
    "2d",
    "anime",
    "fantasy",
    "sci-fi",
    "fighting",
    "action-rpg",
    "action",
    "military",
    "martial-arts",
    "flight",
    "low-spec",
    "tower-defense",
    "horror",
    "mmorts",
  ],
};
